[project]
name = "ai-solemne-2"
version = "0.1.0"
description = "Training YOLOv8 K-Fold y learning rates variations"
authors = [{ name = "Vincent Bustamante" }]
requires-python = ">=3.12   "

[project.dependencies]
torch = "==2.8.0"
pandas = "==2.3.3"
numpy = "==1.26.4"
scikit-learn = "==1.7.2"
ultralytics = "==8.3.213"
pyyaml = "==6.0.3"
opencv-python = ">=4.11.0.86"
matplotlib = ">=3.10.7"
ipython = ">=9.6.0"
